SowthworksApp/SowthworksApp/Controllers/SouthworksEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SowthworksApp.Models;

namespace SowthworksApp.Controllers
{
    public class SouthworksEventController : Controller
    {
        private SouthworksEventDBContext db = new SouthworksEventDBContext();

        //
        // GET: /Events/

        public ActionResult Index()
        {
            return View(db.Events.ToList());           
        }

        [OutputCache(CacheProfile = "ClientCacheEvents")]
        public ActionResult Table()
        {
            return View(db.Events.ToList());
        }

        
        //
        // GET: /Events/Details/5

        [OutputCache(CacheProfile = "CacheEvents")]
        public ActionResult Details(int id = 0)
        {
            SouthworksEvent southworksEvent = db.Events.Find(id);
            if (southworksEvent == null)
            {
                return HttpNotFound();
            }
            return View(southworksEvent);
        }

        //
        // GET: /Events/Create
        public ActionResult Create()
        {
            return View();
        }
        //
        // POST: /Events/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SouthworksEvent southworksEvent)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(southworksEvent);
                db.SaveChanges();
                return RedirectToAction("Table");
            }

            return View(southworksEvent);
        }

        //
        // GET: /Events/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SouthworksEvent southworksEvent = db.Events.Find(id);
            if (southworksEvent == null)
            {
                return HttpNotFound();
            }
            return View(southworksEvent);
        }

        //
        // POST: /Events/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SouthworksEvent southworksEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(southworksEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Table");
            }
            return View(southworksEvent);
        }

        //
        // GET: /Events/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SouthworksEvent southworksEvent = db.Events.Find(id);
            if (southworksEvent == null)
            {
                return HttpNotFound();
            }
            return View(southworksEvent);
        }

        //
        // POST: /Events/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SouthworksEvent southworksEvent = db.Events.Find(id);
            db.Events.Remove(southworksEvent);
            db.SaveChanges();
            return RedirectToAction("Table");
        }

        public ActionResult CreateSouthworksEventAuto()
        {            
            return View();
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSouthworksEventAuto(SouthworksEvent southworksEven)
        {
            List<SouthworksEvent> list = SouthworksEvent.CreateSouthworksEventListAuto();
            
            if (list == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                foreach (var item in list)
                {
                    db.Events.Add(item);
                    db.SaveChanges();
                }
                return RedirectToAction("Table");           
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SowthworksApp/SowthworksApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Southworks Application</title>
        
        @*<script src="~/Scripts/jquery-1.8.2.js"></script>*@
        
        <!-- DataTables CSS -->
        <link rel="stylesheet" type="text/css" href="~/Content/DataTables-1.10.4/css/jquery.dataTables.css">
  
        <!-- jQuery -->       
        <script type="text/javascript" src="~/Scripts/jquery-1.8.2.min.js"></script>
  
        <!-- DataTables -->
        <script type="text/javascript" src="~/Scripts/DataTables-1.10.4/jquery.dataTables.min.js"></script>

        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Southworks APP", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">                            
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Southworks Events", "Table", "SouthworksEvent")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

       @* @Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", required: false)
    </body>
</html>